
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS GrupoParceiros (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NOME VARCHAR(50),
  STATUS VARCHAR(20),
  CONTROLE VARCHAR(50)
);

CREATE UNIQUE INDEX IF NOT EXISTS GRUPOPARCEIROS_CONTROLE_UNQ ON GrupoParceiros (CONTROLE);


CREATE TABLE IF NOT EXISTS GrupoProdutos (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NOME VARCHAR(50),
  STATUS VARCHAR(20),
  CONTROLE VARCHAR(50)
);

CREATE UNIQUE INDEX IF NOT EXISTS GRUPOPRODUTOS_CONTROLE_UNQ ON GrupoProdutos (CONTROLE);

CREATE TABLE IF NOT EXISTS Locacao (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  DESCRICAO VARCHAR(255),
  ENDERECOPADRAO VARCHAR(600),
  STATUS VARCHAR(15),
  CONTROLE VARCHAR(50),
  DATACADASTRO DATETIME,
  USERCADASTRO INTEGER,
  DATAEDICAO DATETIME,
  USEREDICAO INTEGER,
  DATAEXCLUSAO DATETIME,
  USEREXCLUSAO INTEGER,
  TIPO VARCHAR(15)
);

CREATE UNIQUE INDEX IF NOT EXISTS LOCACAO_CONTROLE_UNQ ON Locacao (CONTROLE);

CREATE TABLE IF NOT EXISTS Produtos (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NUMERO VARCHAR(20),
  DESCRICAO VARCHAR(150),
  MARCA VARCHAR(50),
  GRUPO INTEGER,
  UNIDADE VARCHAR(15),
  VALORCOMPRA REAL,
  VALORESTIMADO REAL,
  QUANTIDADEREAL REAL,
  QUANTIDADEESTOQUE REAL,
  VALORMENSAL REAL,
  VALORMINIMO REAL,
  ACESSORIOS VARCHAR(1000),
  PATRIMONIO VARCHAR(40),
  TIPO VARCHAR(6),
  NUMEROSERIE VARCHAR(30),
  TABELADESCONTOMENSAL INTEGER,
  TABELADESCONTODIARIO INTEGER,
  VALORLIMPEZA REAL,
  IDPRODUCAO INTEGER,
  MOSTRACONTRATO VARCHAR(3),
  ACESSORIO VARCHAR(3),
  DESCRICAODETALHADA VARCHAR(7000),
  PRODUCAO INTEGER,
  CONTROLE VARCHAR(50),
  DATACADASTRO DATETIME,
  USERCADASTRO INTEGER,
  DATAEDICAO DATETIME,
  USEREDICAO INTEGER,
  DATAEXCLUSAO DATETIME,
  USEREXCLUSAO INTEGER,
  STATUS VARCHAR(20) GENERATED ALWAYS AS (
    CASE
      WHEN QUANTIDADEESTOQUE <= 0 THEN 'SEM_SALDO'
      ELSE 'ESTOQUE'
    END
  ) VIRTUAL,
  LOCACAO INTEGER,
  LOCACAOANTERIOR INTEGER,
  FOREIGN KEY (GRUPO) REFERENCES GrupoProdutos(ID),
  FOREIGN KEY (LOCACAO) REFERENCES Locacao(ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS PRODUTOS_CONTROLE_UNQ ON Produtos (CONTROLE);
CREATE INDEX IF NOT EXISTS PRODUTOS_GRUPO_IDX ON Produtos (GRUPO);
CREATE INDEX IF NOT EXISTS PRODUTOS_LOCACAO_IDX ON Produtos (LOCACAO);

CREATE TABLE IF NOT EXISTS Parceiros (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  TIPO VARCHAR(8),
  DATACADASTRO DATE,
  GRUPO INTEGER,
  RAZAOSOCIAL VARCHAR(150),
  NOMEFANTASIA VARCHAR(100),
  ENDERECO VARCHAR(100),
  BAIRRO VARCHAR(50),
  CIDADE VARCHAR(50),
  UF VARCHAR(2),
  CEP VARCHAR(10),
  TELEFONE VARCHAR(15),
  CELULAR VARCHAR(15),
  EMAIL VARCHAR(50),
  RG VARCHAR(30),
  CPF VARCHAR(15),
  CNPJ VARCHAR(20),
  IE VARCHAR(30),
  IM VARCHAR(10),
  NASCIMENTO DATE,
  CONTATO VARCHAR(100),
  TELEFONECONTATO VARCHAR(15),
  REPRESENTANTE VARCHAR(100),
  CPFREPRESENTANTE VARCHAR(15),
  TELEFONEREPRESENTANTE VARCHAR(15),
  CELULARREPRESENTANTE VARCHAR(15),
  TIPOFORNECEDOR INTEGER,
  COMISSAO REAL,
  STATUS VARCHAR(9),
  ENDERECOCORRESPONDENCIA VARCHAR(100),
  BAIRROCORRESPONDENCIA VARCHAR(50),
  CIDADECORRESPONDENCIA VARCHAR(50),
  UFCORRESPONDENCIA VARCHAR(2),
  CEPCORRESPONDENCIA VARCHAR(10),
  CAIXAPOSTALCORRESPONDENCIA VARCHAR(20),
  VALORLIMITELOCACAO REAL,
  CONTROLE VARCHAR(100),
  PAI VARCHAR(70),
  MAE VARCHAR(70),
  TIPOPARCEIRO VARCHAR(25),
  OBSERVACAO TEXT,
  ENDERECOREPRESENTANTE VARCHAR(300),
  VENDEDOR INTEGER,
  USERCADASTRO INTEGER,
  DATACAD DATETIME,
  USEREDICAO INTEGER,
  DATAEDICAO DATETIME,
  USERDESBLOQUEIO INTEGER,
  DATADESBLOQUEIO DATETIME,
  USERBLOQUEIO INTEGER,
  DATABLOQUEIO DATETIME,
  COMISSAOCLIENTE REAL,
  ID_4RODAS INTEGER,
  DATAATUALIZACAO DATE,
  HORAATUALIZACAO TIME,
  USERATUALIZACAO INTEGER,
  USERAUTORIZOUATUALIZACAO INTEGER,
  DATAATUALIZACAOANTERIOR DATE,
  HORAATUALIZACAOANTERIOR TIME,
  USERATUALIZACAOANTERIOR INTEGER,
  FOREIGN KEY (GRUPO) REFERENCES GrupoParceiros(ID)
);

CREATE INDEX IF NOT EXISTS PARCEIROS_IDX1 ON Parceiros (VENDEDOR);
CREATE INDEX IF NOT EXISTS PARCEIROS_GRUPO_IDX ON Parceiros (GRUPO);
